"""initial

Revision ID: 108895988081
Revises: d43242eb11ac
Create Date: 2026-03-17 22:28:18.562388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108895988081'
down_revision: Union[str, Sequence[str], None] = 'd43242eb11ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_chat_history_resume_id_resumes'), 'resumes', ['resume_id'], ['id'])

    with op.batch_alter_table('generated_resumes', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_generated_resumes_resume_id_resumes'), 'resumes', ['resume_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_payments_cashfree_order_id'), ['cashfree_order_id'])

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_resumes_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_resumes_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payments_cashfree_order_id'), type_='unique')

    with op.batch_alter_table('generated_resumes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_generated_resumes_resume_id_resumes'), type_='foreignkey')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_history_resume_id_resumes'), type_='foreignkey')

    # ### end Alembic commands ###
