"""add free_downloads_reset_date

Revision ID: 1e753df9fc6b
Revises: 8a5ca58f2dc4
Create Date: 2026-03-23 10:02:09.158583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e753df9fc6b'
down_revision: Union[str, Sequence[str], None] = '8a5ca58f2dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_downloads_reset_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('free_downloads_reset_date')

    # ### end Alembic commands ###
